export const SPOT_MAP_LINKS: Record<string, string> = {
  "Bad people Gdl Vintage Store": "https://maps.app.goo.gl/jmhAX51RtUXMQkGD7",
  "Undisclosed Vintage": "https://maps.app.goo.gl/mpQd51LGqBrfVYZAA",
  "Erica Street Vintage": "https://maps.app.goo.gl/FoatysbZFs1C2JrGA",
  "Bravo Vintage 2": "https://maps.app.goo.gl/nFYA1S7BcpY1wtzR8",
  "Lavanda Vintage": "https://maps.app.goo.gl/jqFphMiCDNWHeDPe6",
  "Dislocal market": "https://maps.app.goo.gl/r4cGEhD12SzX9Az88",
  "Jardín Americana": "https://maps.app.goo.gl/n7BpKMbmEqzUACmZA",
  "Segunda Piel": "https://maps.app.goo.gl/i2KD64VtcUbLGcYq8",
  "D O S T A concept store": "https://maps.app.goo.gl/LL4opu1KQfrZYue76",
  "Archivo GDL": "https://www.google.com/maps/place/ARCHIVOGDL/data=!4m7!3m6!1s0x8428b16f9f9d817b:0xd98c3c213ffb028a!8m2!3d20.6740166!4d-103.3570084!16s%2Fg%2F11tf9lx3r4!19sChIJe4Gdn2-xKIQRigL7PyE8jNk?authuser=0&hl=es&rclk=1",
  "El sótano": "https://www.google.com/maps/place/El+sotano/data=!4m7!3m6!1s0x8428b12d771993b7:0x5f820b4ffb722157!8m2!3d20.6752797!4d-103.3565391!16s%2Fg%2F11h0t2h11l!19sChIJt5MZdy2xKIQRVyFy-08Lgl8?authuser=0&hl=es&rclk=1",
  "El baúl": "https://maps.app.goo.gl/gVu6LoYxT9JFAjXz6",
  "Comunidad Colibrí": "https://maps.app.goo.gl/oPTZQTnDxfERim5r5",
  "Proyecto Mexa": "https://maps.app.goo.gl/tgf49JhmCWp2zPPE6",
  "VÍA LIBERTAD": "https://maps.app.goo.gl/u64bWFv8daEUdvRR7",
  "Casa del Prado": "https://maps.app.goo.gl/tQY4fxF2bwvDszqp9",
  "Casa Sabina Hostal Boutique": "https://maps.app.goo.gl/oX4jSHkSHB7im5156",
  "Almondcoco Boutique": "https://maps.app.goo.gl/zKuxQSjJCdbXuuHCA",
  "Exuvia Showroom": "https://maps.app.goo.gl/z6ZhEUbi5MbNfZEC6",
  "Ohmm Store": "https://maps.app.goo.gl/EcQnYGqtzQus8Zfe6",
  "Mondo Shop": "https://maps.app.goo.gl/FHgRhWHQpULDZKGFA",
  "VACR": "https://maps.app.goo.gl/y5TrwRen9mFu26Zj6",
  "DIVINE 222": "https://maps.app.goo.gl/zZqUoBotkj4REyTZ7",
  "Witch mx": "https://maps.app.goo.gl/qAYTj4ghbiQXUVSr9",
  "Bazar de Muebles y Antiguedades en Guadalajara - Bazar El Viejo del Costal": "https://maps.app.goo.gl/kCNY5EUbXrqwLDA38",
  "Bazar, muebles y antiguedades": "https://www.google.com/maps/place/Bazar,+muebles+y+antiguedades/data=!4m7!3m6!1s0x8428ae172d6b2281:0xa612163fe5c61802!8m2!3d20.6810892!4d-103.3651224!16s%2Fg%2F1tg2k_25!19sChIJgSJrLReuKIQRAhjG5T8WEqY?authuser=0&hl=es&rclk=1",
  "Roxy n roll": "https://maps.app.goo.gl/JoJdJX44QNQKF53PA",
  "Joselino Records": "https://maps.app.goo.gl/zgYpKTjZUeBa7Y6Q8",
  "La Musique Records Guadalajara": "https://maps.app.goo.gl/QQwWNX6CmXtYzzRq9",
  "La Perla Records & Books": "https://maps.app.goo.gl/wf8RY3hPstB7146e6",
  "Bazar La Fortuna": "https://maps.app.goo.gl/gvXd54WV8rFEPNgZ9",
  "Alto Voltaje": "https://maps.app.goo.gl/qx629SXZ2LvJSQ8cA",
  "LIBRERIA DE USADO Y ANTIGUO EL DESVAN DE DON QUIJOTE": "https://maps.app.goo.gl/VKt3mtKyhHH8sYQAA",
  "Librero en andanzas": "https://maps.app.goo.gl/ZAEkghKFQuitCgLW6",
  "Tea Recs": "https://maps.app.goo.gl/w1Dpbmyvqb1Yt27FA",
  "Cosmik Records": "https://maps.app.goo.gl/paXPrQKS2PPSmbUw7",
  "Velvet Records Gdl": "https://maps.app.goo.gl/QrCxcENbSZdKaR6z5",
  "Tianguis del Sol": "https://maps.app.goo.gl/ym1mh91HwoCHtvie7",
  "Tianguis de Mezquitan": "https://maps.app.goo.gl/jT3rK8D7YpiwEx2U6",
  "Tianguis San Juan Bosco": "https://maps.app.goo.gl/NcgNfnn5Y6mB2jcU9",
  "Tianguis de Medrano Calle 66": "https://maps.app.goo.gl/mC4dJPMapQvmJAAX6",
  "Baratillo": "https://maps.app.goo.gl/3fCu1gQatdBmiZ9D8",
  "Tianguis Cultural": "https://maps.app.goo.gl/AdbJx4gTpcHKvAfJ9",
  "Tianguis de Santa Tere": "https://maps.app.goo.gl/8bNT3Pex8gn5TXbM8",
  "Tianguis del trocadero": "https://maps.app.goo.gl/g6SAMEynqRFkgbCy9",
  "Tianguis Francisco Villa / La 74 (Jueves)": "https://maps.app.goo.gl/J1z7SQaWqd9LZ96Z6",
};
