export const SPOT_IMAGES: Record<string, string> = {
  'Bad people Gdl Vintage Store': '/img/spots/01-bad-people-gdl-vintage-store.jpg',
  'Undisclosed Vintage': '/img/spots/02-undisclosed-vintage.jpg',
  'Erica Street Vintage': '/img/spots/03-erica-street-vintage.jpg',
  'Bravo Vintage 2': '/img/spots/04-bravo-vintage-2.jpg',
  'Lavanda Vintage': '/img/spots/05-lavanda-vintage.jpg',
  'Dislocal market': '/img/spots/06-dislocal-market.jpg',
  'Jardín Americana': '/img/spots/07-jardin-americana.jpg',
  'Segunda Piel': '/img/spots/08-segunda-piel.jpg',
  'D O S T A concept store': '/img/spots/09-d-o-s-t-a-concept-store.jpg',
  'Archivo GDL': '/img/spots/10-archivo-gdl.jpg',
  'El sótano': '/img/spots/11-el-sotano.jpg',
  'El baúl': '/img/spots/12-el-baul.jpg',
  'Comunidad Colibrí': '/img/spots/14-comunidad-colibri.jpg',
  'Proyecto Mexa': '/img/spots/16-proyecto-mexa.jpg',
  'Bazar Moda Diseño': '/img/spots/17-bazar-moda-diseno.jpg',
  'VÍA LIBERTAD': '/img/spots/18-via-libertad.jpg',
  'Casa del Prado': '/img/spots/19-casa-del-prado.jpg',
  'Casa Sabina Hostal Boutique': '/img/spots/20-casa-sabina-hostal-boutique.jpg',
  'Almondcoco Boutique': '/img/spots/21-almondcoco-boutique.jpg',
  'Exuvia Showroom': '/img/spots/22-exuvia-showroom.jpg',
  'Ohmm Store': '/img/spots/23-ohmm-store.jpg',
  'Mondo Shop': '/img/spots/24-mondo-shop.jpg',
  VACR: '/img/spots/25-vacr.jpg',
  'DIVINE 222': '/img/spots/26-divine-222.jpg',
  'Witch mx': '/img/spots/28-witch-mx.png',
  'Bazar de Muebles y Antiguedades en Guadalajara - Bazar El Viejo del Costal':
    '/img/spots/29-bazar-de-muebles-y-antiguedades-en-guadalajara-bazar-el-viejo-del-costal.jpg',
  'Roxy n roll': '/img/spots/31-roxy-n-roll.jpg',
  'Joselino Records': '/img/spots/32-joselino-records.jpg',
  'La Musique Records Guadalajara':
    '/img/spots/33-la-musique-records-guadalajara.jpg',
  'La Perla Records & Books': '/img/spots/34-la-perla-records-books.jpg',
  'Bazar La Fortuna': '/img/spots/35-bazar-la-fortuna.jpg',
  'Alto Voltaje': '/img/spots/36-alto-voltaje.jpg',
  LOPA: '/img/spots/37-lopa.jpg',
  'LIBRERIA DE USADO Y ANTIGUO EL DESVAN DE DON QUIJOTE':
    '/img/spots/38-libreria-de-usado-y-antiguo-el-desvan-de-don-quijote.jpg',
  'Librero en andanzas': '/img/spots/39-librero-en-andanzas.jpg',
  'Tea Recs': '/img/spots/40-tea-recs.jpg',
  'Cosmik Records': '/img/spots/41-cosmik-records.jpg',
  'Velvet Records Gdl': '/img/spots/43-velvet-records-gdl.jpg',
};
